esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

ota:
  - platform: esphome
    password: !secret ota_password

status_led:
  pin:
    number: GPIO2
    inverted: true

external_components:
  - source:
      type: local
      path: components
    components: [intercom_remote]
